# Generated by Django 5.0.3 on 2024-09-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_quarto_pessoas_quarto_pessoas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.RemoveField(
            model_name='quarto',
            name='pessoas',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='quarto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='app.quarto'),
            preserve_default=False,
        ),
    ]
