# Generated by Django 5.0.3 on 2024-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cidade_alter_pessoa_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(default=0),
        ),
    ]
