# Generated by Django 5.0.3 on 2024-10-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_curso_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracao',
            field=models.IntegerField(default=5),
        ),
    ]
