# Generated by Django 5.0.3 on 2024-10-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_curso_duracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quarto',
            old_name='numero_quarto',
            new_name='numero',
        ),
    ]
