# Generated by Django 5.0.3 on 2024-10-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_quarto_max_pessoas_quarto_quarto_capacidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='alojamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.alojamento'),
            preserve_default=False,
        ),
    ]
