# Generated by Django 5.0.3 on 2024-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pessoa_alojamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='capacidade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.CharField(max_length=3),
        ),
    ]
