# Generated by Django 5.0.3 on 2024-10-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_quarto_capacidade_alter_quarto_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='alojamento',
        ),
    ]
