# Generated by Django 5.0.3 on 2024-10-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_turma_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='curso',
        ),
    ]
