# Generated by Django 5.0.3 on 2024-10-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_turma_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='app.curso'),
            preserve_default=False,
        ),
    ]
